### ISSUE TITLE
Example for serializing client POST content

### ISSUE THREAD

**Issue by pinx** [cosullivan/Hypermedia#4]
There is an example for deserializing received content, but none for serializing content that I want to post to my backend.
I have been using NewtonSoft for regular JSON. Its JsonSerializerSettings can take a resolver as an argument. Maybe you can make it so, that your resolver can be plugged in.
[sample](http://www.newtonsoft.com/json/help/html/CustomContractResolver.htm).
[API doc](http://www.newtonsoft.com/json/help/html/SerializationSettings.htm)

**Comment by cosullivan** [comment]
Hi, 

There is a Hypermedia.Sample.Client which contains a sample for sending the data back to the server.

I don't think it would work if I made a Json.Net compatible resolver because my resolver simply deals with the metadata of a resource. It would still require JSONAPI formatter that returns the JSON in the appropriate format.

Thanks,
Cain
